version: "3.9"

networks:
  dev:

services:
  #nginx:
  #  image: nginx:stable-alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - './nginx.conf:/etc/nginx/nginx.conf'
  #  depends_on:
  #    - backend
  #    - frontend
  #  networks:
  #    - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    environment:
      - DB_HOST=youtube-postgres
      - DB_NAME=youtube
      - DB_USER=youtube
      - DB_PASSWORD=youtube
      - DB_PORT=5432
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    ports:
      - "4500:4500"
    links:
      - youtube-postgres
    depends_on:
      - youtube-postgres
      - redis
    restart: always

    volumes:
      - ./backend:/backend  # Монтируем директорию app с хоста в контейнер
      - ./video:/video  # Монтируем директорию videos с хоста в контейнер
      - ./audio:/audio  # Монтируем директорию audio с хоста в контейнер

    working_dir: /backend

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    ports:
      - "3000:3000"
    
  youtube-postgres:
    image: "postgres:13.3-alpine"
    container_name: youtube-postgres
    volumes:
      - youtube-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: youtube

      POSTGRES_USER: youtube
      POSTGRES_PASSWORD: youtube
    networks:
      - dev

  userbot:
    build:
      context: ./userbot
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    networks:
      - dev
    depends_on:
      - redis
    restart: always
    volumes:
      - ./userbot:/userbot  # Монтируем директорию app с хоста в контейнер
      - ./video:/video  # Монтируем директорию video с хоста в контейнер
      - ./audio:/audio  # Монтируем директорию audio с хоста в контейнер
      - ./userbot/USERBOT.session:/userbot/USERBOT.session
    working_dir: /userbot

  downloader:
    build:
      context: ./downloader
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - dev
    depends_on:
      - redis
    restart: always
    volumes:
      - ./downloader:/downloader  # Монтируем директорию app с хоста в контейнер
      - ./video:/video  # Монтируем директорию video с хоста в контейнер
      - ./audio:/audio  # Монтируем директорию audio с хоста в контейнер
    working_dir: /downloader

  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - dev


volumes:
  youtube-data:

